import { BoardCategory } from '@/board/type';

export const boardList = [
  {
    boardId: 1,
    title: '질문이 있어요',
    body: '질문질문',
    date: '2024-04-21',
    boardCategory: BoardCategory.QUESTION,
    commentCount: 0,
    courseTitle: '강좌1',
    lectureTitle: '강좌2',
  },
  {
    boardId: 2,
    title: '질문이 있어요',
    body: '질문질문',
    date: '2024-04-21',
    boardCategory: BoardCategory.QUESTION,
    commentCount: 0,
    courseTitle: '강좌1',
    lectureTitle: '강좌2',
  },
  {
    boardId: 3,
    title: '질문이 있어요',
    body: '질문질문',
    date: '2024-04-21',
    boardCategory: BoardCategory.QUESTION,
    commentCount: 0,
    courseTitle: '강좌1',
    lectureTitle: '강좌2',
  },
  {
    boardId: 4,
    title: '질문이 있어요',
    body: '질문질문',
    date: '2024-04-21',
    boardCategory: BoardCategory.QUESTION,
    commentCount: 0,
    courseTitle: '강좌1',
    lectureTitle: '강좌2',
  },
  {
    boardId: 5,
    title: '질문이 있어요',
    body: '질문질문',
    date: '2024-04-21',
    boardCategory: BoardCategory.QUESTION,
    commentCount: 0,
    courseTitle: '강좌1',
    lectureTitle: '강좌2',
  },
  {
    boardId: 6,
    title: '질문이 있어요',
    body: '질문질문',
    date: '2024-04-21',
    boardCategory: BoardCategory.QUESTION,
    commentCount: 0,
    courseTitle: '강좌1',
    lectureTitle: '강좌2',
  },
];
