import { BoardCategory } from '@/board/BoardItem';

export const boardList = [
  {
    id: '1',
    title: '질문이 있어요',
    content: '질문질문',
    date: '2024-04-21',
    category: BoardCategory.QUESTION,
    commentCount: 0,
    courseTitle: '강좌1',
    lectureTitle: '강좌2',
  },
  {
    id: '2',
    title: '질문이 있어요',
    content: '질문질문',
    date: '2024-04-21',
    category: BoardCategory.QUESTION,
    commentCount: 0,
    courseTitle: '강좌1',
    lectureTitle: '강좌2',
  },
  {
    id: '3',
    title: '질문이 있어요',
    content: '질문질문',
    date: '2024-04-21',
    category: BoardCategory.QUESTION,
    commentCount: 0,
    courseTitle: '강좌1',
    lectureTitle: '강좌2',
  },
  {
    id: '4',
    title: '질문이 있어요',
    content: '질문질문',
    date: '2024-04-21',
    category: BoardCategory.QUESTION,
    commentCount: 0,
    courseTitle: '강좌1',
    lectureTitle: '강좌2',
  },
  {
    id: '5',
    title: '질문이 있어요',
    content: '질문질문',
    date: '2024-04-21',
    category: BoardCategory.QUESTION,
    commentCount: 0,
    courseTitle: '강좌1',
    lectureTitle: '강좌2',
  },
  {
    id: '6',
    title: '질문이 있어요',
    content: '질문질문',
    date: '2024-04-21',
    category: BoardCategory.QUESTION,
    commentCount: 0,
    courseTitle: '강좌1',
    lectureTitle: '강좌2',
  },
];
